language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
#  - "3.6"
#  - "3.7"

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
#  - pip install codecov
#  - pip install datetime
#  - pip install python-dateutil

script:
  # Notes on nose:
  # Travis CI pre-installs `nose`
  # https://github.com/coagulant/coveralls-python#nosetests
  # http://nose.readthedocs.org/en/latest/plugins/skip.html
  - nosetests --no-skip --with-coverage test_flexidate.py

after_success:
  - codecov
